server:
  port: 8080

spring:
  application:
    name: weixin-service

elasticjob:
  reg-center:
    # 命名空间，必须以elasticJob开头，以应用编码结尾。例: namespace: elasticJob/weixin-service
    namespace: elasticJob/${spring.application.name}
    server-lists: 127.0.0.1:2181
  jobs:
    mySimpleJob:
      elasticJobClass: com.hoshino.springboot.elasticjob.jobs.MySimpleJob
      cron: "0/10 * * * * ?"
      shardingTotalCount: 3
      overwrite: false