server:
  port: 8050
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 2000ms
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 7
        # 连接池中的最大空闲连接 默认为8
        max-idle: 7
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 1
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: 1ms

logging:
  level:
    ROOT: INFO