server:
  port: 8082

spring:
  application:
    name: user-provider

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
    timeout: 5000
  config-center:
    address: zookeeper://127.0.0.1:2181
    timeout: 5000
  metadata-report:
    address: zookeeper://127.0.0.1:2181
    timeout: 5000
