server:
  port: 8080

spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://127.0.0.1:3306/master?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 123456
      slave:
        url: jdbc:mysql://127.0.0.1:3306/slave?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 123456
      dynamic1:
        url: jdbc:mysql://127.0.0.1:3306/dynamic1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 123456
      dynamic2:
        url: jdbc:mysql://127.0.0.1:3306/dynamic2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 123456

mybatis-config:
  master:
    mapperXml: com.hoshino.springboot.multisource.dao.master.mapper.*Mapper.xml
    typeAliasesPackage: classpath:com.hoshino.springboot.multisource.entity.master.**
  slave:
    mapperXml: com.hoshino.springboot.multisource.dao.slave.mapper.*Mapper.xml
    typeAliasesPackage: classpath:com.hoshino.springboot.multisource.entity.slave.**
  dynamic:
    mapperXml: com.hoshino.springboot.multisource.dao.dynamic.mapper.*Mapper.xml
    typeAliasesPackage: classpath:com.hoshino.springboot.multisource.entity.dynamic.**
