server:
  port: 8084

spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 指定消息在没有被队列接收时是否强行退回还是直接丢弃
    template:
      mandatory: true
    # 确认消息已发送到交换机(Exchange)，新版本 publisher-confirms: true 已过时
    # none：表示禁用发布确认模式，默认值，使用此模式之后，不管消息有没有发送到 Broker 都不会触发 ConfirmCallback 回调。
    # correlated：表示消息成功到达 Broker 后触发 ConfirmCallBack 回调。
    # simple：simple 模式下如果消息成功到达Broker后一样会触发 ConfirmCallBack 回调
    # 发布消息成功后使用 rabbitTemplate 调用 waitForConfirms 或 waitForConfirmsOrDie 方法等待 Broker 节点返回发送结果，根据返回结果来判定下一步的逻辑
    # 注意：waitForConfirmsOrDie 方法如果返回 false 则会关闭 channel 信道，则接下来无法发送消息到 Broker。
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)，true 表示开启失败回调，开启后当消息无法路由到指定队列时会触发 ReturnCallback 回调。
    publisher-returns: true

